# Generated by Django 5.0.1 on 2024-02-18 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LittleMangoAPI', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='slog',
            new_name='slug',
        ),
    ]
