# Generated by Django 5.0.1 on 2024-03-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LittleMangoAPI', '0004_alter_cart_price_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
